<script setup>

</script>

<template>
  <div class="home">
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
    <div>这是首页</div>
  </div>
</template>

<style scoped>
.home {
}
</style>