---
spring:
  # 生产环境使用 jndi
  datasource:
    jndi-name: jdbc/test

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0

logging:
  file:
    path: /tmp/logs/

...